### PR TITLE
Upgrade to ember-cli 0.2.7

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Upgrade to ember-cli 0.2.7 and let ember init update files as needed while maintaining existing dependencies and functionality

### CODE REVIEW

**Comment by bguiz** [comment]
@Dhaulagiri Thanks for the patch, I have merged this in but I have not cut a new release. If you're happy for me to do so, or have any more additions, let me know.

**Comment by Dhaulagiri** [comment]
I'm working on another PR to allow for creating more than one sprite. Once that is finished and merged a new release would be helpful.

**Comment by bguiz** [comment]
OK, but you're happy with this one as it is? I'd prefer to do a different release for an unrelated feature.

And thanks in advance for the patch in the works!

**Comment by Dhaulagiri** [comment]
Good point.  I should update the readme as part of the 0.2.7 upgrade.  I'll submit something for that today.

**Pull request merged**
