### PR TITLE
Make ember-sprite run before broccoli-asset-rev

### LINKED ISSUE #9: ember-sprite incompatible with broccoli-asset-rev
When I trigger a production build of my ember-cli app like so:

```
ember build -e production
```

I get the following error:

```
Path or pattern "assets/myapp.css" did not match any files
```

This is because the file `myapp.css` has been renamed to `myapp-cbabcba3bcabcb3a3bca3.css` by broccoli-asset-rev.

Therefore ember-sprite cannot complete the css concatenation correctly and the build fails.

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Fixes #9

### CODE REVIEW

**Comment by bguiz** [comment]
Thanks for this!

BTW just a heads up, I've just moved this repo to git-flow, future branches off `develop` instead of `master` (I've switched the main branch too to `develop` too)

**Comment by Dhaulagiri** [comment]
:+1: @bguiz

**Comment by Dhaulagiri** [comment]
Please let me know when you cut a new release

**Comment by bguiz** [comment]
I'm planning on doing that tomorrow. I'll ping you on this thread when I
do, of course.

W: http://bguiz.com

**Comment by bguiz** [comment]
Released [v0.4.0](https://www.npmjs.com/package/ember-sprite)

W: http://bguiz.com

**Pull request merged**
