### PR TITLE
Remove source images

### PR DESCRIPTION
**Pull request by puwelous**
This PR targets a couple of issues: 

- replaces usage of deprecated broccoli dependencies with a supported ones
- enables removal of source images used for a sprite generation
- imports reordering and variables refactoring

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
Thanks for taking this on!

> replaces usage of deprecated broccoli dependencies with a supported ones

do you know which deprecations you were addressing?

> enables removal of source images used for a sprite generation

I think I understand the code for this but couldn't quite grok how to verify the files were getting removed, is there a way to confirm they've gotten removed or what is the benefit of this?

**Comment by puwelous** [comment]
> do you know which deprecations you were addressing?
Both dependencies are deprecated in favour of `broccoli-funnel`
https://github.com/rwjblue/broccoli-file-remover
https://github.com/joliss/broccoli-static-compiler

> how to verify the files were getting removed
This is an extension to cover needs within our project and we use it in production :) if you have an idea how to test this, let me know ;)

**Comment by Dhaulagiri** [comment]
Excellent, thanks. I think there is still a fundamental deprecation in how this addon uses broccoli that can be addresses separately.

**Comment by Dhaulagiri** [comment]
published in 0.9.0

**Pull request merged**
